### ISSUE TITLE
Has an issue in StrictMode

### ISSUE THREAD

**Issue by embeddedt** [daybrush/css-styled#4]
I've found that this library generates an error when used with React's strict mode. It looks like it would be straightforward to fix - [this code](https://github.com/daybrush/css-styler/blob/master/react-css-styler/src/react-css-styler/styled.tsx) just needs to be switched to using refs instead of using findDOMNode.

```
Warning: findDOMNode is deprecated in StrictMode. findDOMNode was passed an instance of Styler which is inside StrictMode. Instead, add a ref directly to the element you want to reference. Learn more about using refs safely here: https://fb.me/react-strict-mode-find-node
    in div (created by Styler)
    in Styler (created by MoveableManager)
    in MoveableManager (created by Moveable)
    in Moveable
```

**Comment by daybrush** [comment]
@embeddedt 

Thank you for reporting react bug  and sorry to see this issue now.

I will fix this problem soon.
