### ISSUE TITLE
Undefined version cause crash in non-react apps

### ISSUE THREAD

**Issue by jvnm-dev** [daybrush/css-styled#5]
The following commit cause an issue in project using this library:
https://github.com/daybrush/css-styled/commit/ac6a2b34b541b08d6fc393c75387237663ac7d19

Line that causes the issue:
https://github.com/daybrush/css-styled/commit/ac6a2b34b541b08d6fc393c75387237663ac7d19#diff-0e825ed2f2470d57c43b731b2eea9bbf05aef8e9d1e091b017b56ecd094609eaR22

My situation: I am using the library [moveable](https://github.com/daybrush/moveable/) in a non-react app.
Since there is no react version, its value is `undefined` so it crashes when doing `.indexOf` (cannot read indexOf of undefined)

@daybrush Could you check if the version exists before doing the indexOf ? Like:
`if ((version ?? '').indexOf("simple") > -1 && portalContainer) {`

Thank you

**Comment by daybrush** [comment]
@jvnm-dev 

Perhaps it is a dependency problem.

The version of react-simple-compat needs to be updated, but it seems to be a problem. Would you like to delete the moveable and reinstall it?

**Comment by jvnm-dev** [comment]
Thank you, you solved the issue with your last commit 👍🏻
